app_deployment:
  appName: video-manager-converter
  image: nexus-docker-craigmiller160.ddns.net/video-manager-converter:latest
  configMap:
    spring.profiles.active: prod
    spring.datasource.url: jdbc:postgresql://postgres.infra-prod:5432/video_manager_converter
    spring.security.oauth2.resourceserver.jwt.issuer-uri: https://auth-craigmiller160.ddns.net/realms/apps-prod
  onepassworditems:
    - name: video-converter-postgres
      itemPath: vaults/Home Server (Prod)/items/Postgres Root Account
  ports:
    - containerPort: 8080
  secrets:
    - envVariable: spring.datasource.username
      secretName: video-manager-postgres
      secretKey: username
    - envVariable: spring.datasource.password
      secretName: video-manager-postgres
      secretKey: password
  commonProbe:
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTP
  volumes:
    - name: video-manager-converter-volume-homedir
      type: HostPath
      deploymentMountPath: /opt/video-manager/homeDir
      hostPath: /home/craig