version: '3.5'

services:
  postgres:
    image: postgres:14.5
    container_name: vm_converter_postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
